from typing import Any, Dict


CANDIDATE_DB: Dict[str, Dict[str, Any]] = {
    "C-1001": {
        "name": "Aarav Mehta",
        "years_experience": 4,
        "current_ctc_lpa": 8.0,
        "expected_salary_lpa": 9.2,
        "skills": ["python", "sql", "airflow", "pandas"],
        "education": "B.Tech Computer Science",
        "location": "Bengaluru",
        "risk_flags": [],
        "summary": "Data engineer with production ETL ownership and strong Python foundations.",
    },
    "C-1002": {
        "name": "Riya Sharma",
        "years_experience": 3,
        "current_ctc_lpa": 10.0,
        "expected_salary_lpa": 12.5,
        "skills": ["python", "django", "postgres", "aws"],
        "education": "B.E Information Technology",
        "location": "Pune",
        "risk_flags": [],
        "summary": "Backend developer with strong API design and ownership experience.",
    },
    "C-1003": {
        "name": "Kabir Rao",
        "years_experience": 5,
        "current_ctc_lpa": 11.0,
        "expected_salary_lpa": 14.0,
        "skills": ["java", "spring", "kafka", "mysql"],
        "education": "B.Tech Electronics",
        "location": "Hyderabad",
        "risk_flags": [],
        "summary": "Platform engineer with strong distributed systems background.",
    },
    "C-2001": {
        "name": "Neha Iyer",
        "years_experience": 6,
        "current_ctc_lpa": 15.0,
        "expected_salary_lpa": 18.0,
        "skills": ["react", "typescript", "node", "graphql"],
        "education": "B.Sc Computer Science",
        "location": "Chennai",
        "risk_flags": [],
        "summary": "Full-stack product engineer with excellent frontend architecture depth.",
    },
    "C-2002": {
        "name": "Sanya Kulkarni",
        "years_experience": 5,
        "current_ctc_lpa": 8.2,
        "expected_salary_lpa": 9.8,
        "skills": ["python", "fastapi", "sql", "docker"],
        "education": "MCA",
        "location": "Mumbai",
        "risk_flags": [],
        "summary": "API engineer specializing in Python services and backend reliability.",
    },
    "C-2003": {
        "name": "Varun Singh",
        "years_experience": 4,
        "current_ctc_lpa": 7.5,
        "expected_salary_lpa": 8.8,
        "skills": ["python", "excel", "tableau", "sql"],
        "education": "B.Com",
        "location": "Delhi",
        "risk_flags": ["weaker_cs_fundamentals"],
        "summary": "Analyst transitioning to data engineering with practical Python usage.",
    },
    "C-3001": {
        "name": "Ishita Verma",
        "years_experience": 7,
        "current_ctc_lpa": 13.0,
        "expected_salary_lpa": 15.5,
        "skills": ["python", "spark", "ml", "aws"],
        "education": "B.Tech + PG Diploma AI",
        "location": "Bengaluru",
        "risk_flags": [],
        "summary": "ML platform engineer with deep data pipeline and model deployment experience.",
    },
    "C-3002": {
        "name": "Arjun Patel",
        "years_experience": 5,
        "current_ctc_lpa": 7.8,
        "expected_salary_lpa": 9.6,
        "skills": ["python", "flask", "redis", "postgres"],
        "education": "B.Tech Information Science",
        "location": "Ahmedabad",
        "risk_flags": [],
        "summary": "Backend engineer experienced in high-throughput APIs and caching.",
    },
    "C-3003": {
        "name": "Mira Joseph",
        "years_experience": 8,
        "current_ctc_lpa": 16.0,
        "expected_salary_lpa": 20.0,
        "skills": ["python", "kubernetes", "terraform", "gcp"],
        "education": "B.Tech Computer Science",
        "location": "Kochi",
        "risk_flags": [],
        "summary": "Infrastructure-focused engineer with strong cloud and automation exposure.",
    },
    "C-3004": {
        "name": "Dev Malhotra",
        "years_experience": 3,
        "current_ctc_lpa": 6.0,
        "expected_salary_lpa": 7.4,
        "skills": ["javascript", "node", "mongodb", "express"],
        "education": "BCA",
        "location": "Noida",
        "risk_flags": [],
        "summary": "Generalist backend engineer with strong Node.js delivery record.",
    },
}


TASKS: Dict[str, Dict[str, Any]] = {
    "easy_task": {
        "difficulty": "easy",
        "title": "Profile retrieval and shortlist basics",
        "objective": "Find and shortlist one Python-ready backend candidate from a small pool.",
        "max_steps": 10,
        "api_budget": 4,
        "candidate_ids": ["C-1001", "C-1002", "C-1003"],
        "target_shortlist": ["C-1001"],
        "required_skills": ["python"],
        "salary_cap_lpa": 11.0,
    },
    "medium_task": {
        "difficulty": "medium",
        "title": "Role-fit precision shortlist",
        "objective": "Shortlist exactly one Python backend candidate with strong service experience and controlled compensation.",
        "max_steps": 14,
        "api_budget": 5,
        "candidate_ids": ["C-2001", "C-2002", "C-2003"],
        "target_shortlist": ["C-2002"],
        "required_skills": ["python", "fastapi", "sql"],
        "salary_cap_lpa": 10.0,
    },
    "hard_task": {
        "difficulty": "hard",
        "title": "Multi-variable optimization under budget",
        "objective": "Build a two-candidate shortlist with strong Python backend fundamentals while strictly staying within 10 LPA salary cap per candidate and API-call limits.",
        "max_steps": 20,
        "api_budget": 6,
        "candidate_ids": ["C-3001", "C-3002", "C-3003", "C-3004"],
        "target_shortlist": ["C-3002"],
        "required_skills": ["python", "postgres"],
        "salary_cap_lpa": 10.0,
    },
}